services:
  postgres:
    image: postgres:18-alpine
    restart: unless-stopped
    container_name: price_db
    environment:
      POSTGRES_USER: quantfox
      POSTGRES_PASSWORD: quantfox
      POSTGRES_DB: quantfox
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U quantfox -d quantfox"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - my_network
  redis:
    image: redis:8-alpine
    restart: unless-stopped
    container_name: price_redis
    ports:
      - 6379:6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - my_network
  python-api:
    image: python-api:latest
    pull_policy: never
    build:
      context: python-api/
    restart: unless-stopped
    container_name: price_python
    ports:
      - 8081:8081
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/v1/healthy"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - my_network
  celery-worker:
    image: python-api:latest
    pull_policy: never
    build:
      context: python-api/
    restart: unless-stopped
    container_name: price_celery
    command: celery -A src.celery:celery_app worker --loglevel=info
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - my_network
  rust-api:
    image: rust-api:latest
    pull_policy: never
    build:
      context: rust-api/
    restart: unless-stopped
    container_name: price_rust
    ports:
      - 8080:8080
    depends_on:
      python-api:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/v1/healthy"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - my_network

volumes:
  pgdata:

networks:
  my_network:
