services:
  postgres:
    image: postgres:18-alpine
    restart: unless-stopped
    container_name: price_db
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_DB}
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USER} -d ${DATABASE_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
  python-api:
    image: python-api:latest
    pull_policy: never
    build:
      context: python-api/
    restart: unless-stopped
    container_name: python_api
    ports:
      - 8081:8081
    depends_on:
      postgres:
        condition: service_healthy
  rust-api:
    image: rust-api:latest
    pull_policy: never
    build:
      context: rust-api/
    restart: unless-stopped
    container_name: price_rust
    ports:
      - 8080:8080
    depends_on:
      - python-api

volumes:
  pgdata:
